import psycopg2
import os
import logging
from dotenv import load_dotenv

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

load_dotenv()

# Comprehensive mapping for remaining Unknown cities
NEW_MAPPINGS = {
    # High count cities
    "gujar khan": "Punjab",
    "shorkot": "Punjab",
    "theeng more": "Punjab",
    "timergara": "Khyber Pakhtunkhwa",
    "khuddian khas": "Punjab",
    "talagang": "Punjab",
    "minchinabad": "Punjab",
    "pakpattan": "Punjab",
    "dinga": "Punjab",
    "phalia": "Punjab",
    "murree": "Punjab",
    "hasilpur": "Punjab",
    "daharki": "Sindh",
    "sanghar": "Sindh",
    "moro": "Sindh",
    "jampur": "Punjab",
    "sakrand": "Sindh",
    "jalalpur jattan": "Punjab",
    "ahmed pur east": "Punjab",
    "rahimyar khan": "Punjab",
    "rahim yar khan": "Punjab",
    "alipur": "Punjab",
    "ali pur": "Punjab",
    "dina": "Punjab",
    "pasrur": "Punjab",
    "kot radha kishan": "Punjab",
    "basirpur": "Punjab",
    "shahdadpur": "Sindh",
    "abottabad": "Khyber Pakhtunkhwa",
    "abbottabad": "Khyber Pakhtunkhwa",
    "matli": "Sindh",
    "arif wala": "Punjab",
    "arifwala": "Punjab",
    "lalamusa": "Punjab",
    "lala musa": "Punjab",
    "joharabad": "Punjab",
    "jauharabad": "Punjab",
    "fateh jang": "Punjab",
    "ranipur": "Sindh",
    "mian channu": "Punjab",
    "mian channun": "Punjab",
    "mian chanoo": "Punjab",
    "tando muhammad khan": "Sindh",
    "muzafarabad": "Azad Kashmir",
    "muzaffarabad": "Azad Kashmir",
    "pir mahal": "Punjab",
    "pirmahal": "Punjab",
    "pind dadan khan": "Punjab",
    "digri": "Sindh",
    "kala shah kaku": "Punjab",
    "kunri": "Sindh",
    "abdul hakim": "Punjab",
    "mithi": "Sindh",
    "noshehro feroz": "Sindh",
    "naushahro firoz": "Sindh",
    "noushehro feroz": "Sindh",
    "farooqabad": "Punjab",
    "sara - e - alamgir": "Punjab",
    "sarai alamgir": "Punjab",
    "mangla": "Azad Kashmir",
    "pahrianwala": "Punjab",
    "shakar garh": "Punjab",
    "jahanian": "Punjab",
    "bhawalpur": "Punjab",
    "bahawalpur": "Punjab",
    "thul": "Sindh",
    "hala": "Sindh",
    "buner": "Khyber Pakhtunkhwa",
    "piplan": "Punjab",
    "jalal pur bhattian": "Punjab",
    "jalalpur bhattian": "Punjab",
    "samandri": "Punjab",
    "samundri": "Punjab",
    "kandh kot": "Sindh",
    "kandhkot": "Sindh",
    "jalal pur pirwala": "Punjab",
    "depalpur": "Punjab",
    "depal pur": "Punjab",
    "chunian": "Punjab",
    "risalpur": "Khyber Pakhtunkhwa",
    "chashma": "Punjab",
    "jehlum": "Punjab",
    "jhelum": "Punjab",
    "bhera": "Punjab",
    "narang mandi": "Punjab",
    "kamber ali khan": "Sindh",
    "khurian wala": "Punjab",
    "khurrianwala": "Punjab",
    "sangla hill": "Punjab",
    "master head office": "Punjab",
    "chowk azam": "Punjab",
    "zafarwal": "Punjab",
    "pano aqil": "Sindh",
    "pannu akil": "Sindh",
    "shor kot": "Punjab",
    "dera murad jamali": "Balochistan",
    "hujra shah muqim": "Punjab",
    "hujra shah muqeem": "Punjab",
    "kallar saidan": "Punjab",
    "liaquatpur": "Punjab",
    "qila deedar singh": "Punjab",
    # Additional variations
    "toba tek singh": "Punjab",
    "toba take singh": "Punjab",
    "topi": "Khyber Pakhtunkhwa",
    "tulamba": "Punjab",
    "choa saidan shah": "Punjab",
    "chiniot": "Punjab",
    "chinniot": "Punjab",
    "chuhar jamali": "Sindh",
    "chowk sarwar shaheed": "Punjab",
    "drosh": "Khyber Pakhtunkhwa",
    "dir": "Khyber Pakhtunkhwa",
    "dir kpk": "Khyber Pakhtunkhwa",
    "dhirkot": "Azad Kashmir",
    "dera allah yar": "Balochistan",
    "dera allahyar": "Balochistan",
    "dera alayar": "Balochistan",
    "darro": "Sindh",
    "dadyal": "Azad Kashmir",
    "nowshehra": "Khyber Pakhtunkhwa",
    "nowshera": "Khyber Pakhtunkhwa",
    "phularwan": "Punjab",
    "pindi bhattian": "Punjab",
    "pindi bhatian": "Punjab",
    "pindigheb": "Punjab",
    "pindi gheb": "Punjab",
    "pindi saidpur": "Punjab",
    "tharo shah": "Sindh",
    "ellah abad": "Punjab",
    "dunyapur": "Punjab",
    "duniapur": "Punjab",
    "nakyal": "Azad Kashmir",
    "naudero": "Sindh",
    "tranda muhammad panah": "Sindh",
    "panjgur": "Balochistan",
    "chuniya": "Punjab",
    # More additions from v8b
    "yazman mandi": "Punjab",
    "usta mohammad": "Balochistan",
    "jhanian": "Punjab",
    "chak jhumra": "Punjab",
    "tarbela": "Khyber Pakhtunkhwa",
    "jand": "Punjab",
    "qaboola": "Punjab",
    "shah kot": "Punjab",
    "shahkot": "Punjab",
    "sillanwali": "Punjab",
    "tandlianwala": "Punjab",
    "sharaqpur shareef": "Punjab",
    "sharaqpur sharif": "Punjab",
    "malakwal": "Punjab",
    "haroon abad": "Punjab",
    "haroonabad": "Punjab",
    "kot mithan": "Punjab",
    "mandi faizabad": "Punjab",
    "khudiyan khas": "Punjab",
    "hasan abdal": "Punjab",
    "hasanabdal": "Punjab",
    "laki marwat": "Khyber Pakhtunkhwa",
    "lakki marwat": "Khyber Pakhtunkhwa",
    "johi": "Sindh",
    "kahuta": "Punjab",
    "rawat": "Punjab",
    "jatoi": "Punjab",
    "bhawana": "Punjab",
    "feroze wattan": "Punjab",
    "feroz watowan": "Punjab",
    "fateh pur": "Punjab",
    "fatehpur": "Punjab",
    "kallar syedan": "Punjab",
    "kallar kahar": "Punjab",
    "rato dero": "Sindh",
    "ahmed pur sial": "Punjab",
    "kabir wala": "Punjab",
    "kabirwala": "Punjab",
    "darya khan": "Punjab",
    "haveli lakha": "Punjab",
    "kot momin": "Punjab",
    "gaggo mandi": "Punjab",
    "gago mandi": "Punjab",
    "shabqadar": "Khyber Pakhtunkhwa",
    "guddu": "Sindh",
    "umer kot": "Sindh",
    "umerkot": "Sindh",
    "warburton": "Punjab",
    "shinkiari": "Khyber Pakhtunkhwa",
    "safdarabad": "Punjab",
    "sujawal": "Sindh",
    "mingora": "Khyber Pakhtunkhwa",
    "mingaora": "Khyber Pakhtunkhwa",
    "havelian": "Khyber Pakhtunkhwa",
    "changa manga": "Punjab",
    "ubauro": "Sindh",
    "ubaro": "Sindh",
    "badiana": "Punjab",
    "rajana": "Punjab",
    "pallandri": "Azad Kashmir",
    "nasirabad": "Balochistan",
    "dadyal ajk": "Azad Kashmir",
    "kahror pacca": "Punjab",
    "faqirwali": "Punjab",
    "faqir wali": "Punjab",
    "islamkot": "Sindh",
    "fort abbas": "Punjab",
    "shahdad kot": "Sindh",
    "kalat": "Balochistan",
    "shinkayari": "Khyber Pakhtunkhwa",
    "uthal": "Balochistan",
    "18 hazari city": "Punjab",
    "jhuddo": "Sindh"
}

def fix_provinces():
    try:
        conn = psycopg2.connect(
            host=os.getenv('PG_HOST'),
            database=os.getenv('PG_DB'),
            user=os.getenv('PG_USER'),
            password=os.getenv('PG_PASSWORD'),
            sslmode='require'
        )
        cur = conn.cursor()
        
        logger.info("Starting province backfill v8...")
        total_updated = 0
        
        for city, province in NEW_MAPPINGS.items():
            cur.execute("""
                UPDATE orders 
                SET province = %s 
                WHERE LOWER(TRIM(customer_city)) = %s 
                AND (province IS NULL OR province = '' OR UPPER(province) IN ('UNKNOWN', 'OTHER', 'N/A'))
            """, (province, city))
            count = cur.rowcount
            if count > 0:
                logger.info(f"Updated {count} orders for {city} -> {province}")
                total_updated += count
        
        conn.commit()
        logger.info(f"Total orders updated: {total_updated}")
        conn.close()
        
    except Exception as e:
        logger.error(f"Error: {e}")

if __name__ == "__main__":
    fix_provinces()
